#! /bin/sh

source ~/.config/bspwm/profile

sxhkd &

#randwallpaper

compton --config /home/jaume/.config/compton &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
#bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

#bspc monitor -d I II III IV V VI VII VIII IX X

if [[ $(bspc query -M | wc -l) -eq 2 ]]; then
	if [[ $(hostname) = "altair" ]]; then
		bspc monitor HDMI-0 -n R
		bspc monitor DVI-I-1 -n L
	elif [[ $(hostname) = "evangelion" ]]; then
		bspc monitor DP1 -n L
		bspc monitor eDP1 -n R
	else
		bspc monitor ^1 -n L
		bspc monitor ^2 -n R
	fi
	#bspc monitor R -s L
	bspc monitor L -d I II III IV V VI VII VIII IX X
	bspc monitor R -d I II III IV V VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

#bspc rule -a mplayer2 state=floating
bspc rule -a Steam follow=no floating=on

panel &

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi
