-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[7-Zip FM]====], [====[7zFM]====]},
{[====[About Xfce]====], [====[xfce4-about]====]},
{[====[Archive Manager]====], [====[file-roller]====]},
{[====[File Manager]====], [====[exo-open --launch FileManager %u]====]},
{[====[Graphical Disk Map]====], [====[gdmap]====]},
{[====[KeePassX]====], [====[keepassx %f]====]},
{[====[Open a New Window]====], [====[terminator]====]},
{[====[Screenshot]====], [====[xfce4-screenshooter]====]},
{[====[Terminal Emulator]====], [====[exo-open --launch TerminalEmulator]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
{[====[Amnesia The Dark Descent]====], [====[steam steam://rungameid/57300]====]},
{[====[Bastion]====], [====[steam steam://rungameid/107100]====]},
{[====[Counter-Strike]====], [====[steam steam://rungameid/10]====]},
{[====[DeSmuME (Gtk)]====], [====[desmume]====]},
{[====[Dolphin]====], [====[dolphin-emu]====]},
{[====[Dungeon Crawl Stone Soup]====], [====[crawl-tiles]====]},
{[====[Dungeon Defenders]====], [====[steam steam://rungameid/65800]====]},
{[====[FlightGear]====], [====[fgfs --fg-root=/usr/share/flightgear/data]====]},
{[====[Frozen Synapse]====], [====[steam steam://rungameid/98200]====]},
{[====[Half-Life]====], [====[steam steam://rungameid/70]====]},
{[====[Minetest]====], [====[minetest]====]},
{[====[PCSX]====], [====[pcsx]====]},
{[====[PCSX2]====], [====[pcsx2]====]},
{[====[Psychonauts]====], [====[steam steam://rungameid/3830]====]},
{[====[Rochard]====], [====[steam steam://rungameid/107800]====]},
{[====[Shatter]====], [====[steam steam://rungameid/20820]====]},
{[====[Space Pirates and Zombies]====], [====[steam steam://rungameid/107200]====]},
{[====[Superbrothers Sword & Sworcery EP]====], [====[steam steam://rungameid/204060]====]},
{[====[Team Fortress 2]====], [====[steam steam://rungameid/440]====]},
{[====[TORCS]====], [====[torcs]====]},
{[====[VBA-M]====], [====[gvbam %f]====]},
{[====[Xonotic (GLX)]====], [====[/usr/bin/xonotic-glx]====]},
{[====[Xonotic (SDL)]====], [====[/usr/bin/xonotic-sdl]====]}
}
applicationsmenu[40] = {
{[====[Blender]====], [====[blender]====]},
{[====[GNU Image Manipulation Program]====], [====[gimp-2.8]====]},
{[====[Image Viewer]====], [====[eog]====]},
{[====[Inkscape]====], [====[inkscape %F]====]},
{[====[mtPaint]====], [====[mtpaint %F]====]},
{[====[MyPaint]====], [====[mypaint %f]====]}
}
applicationsmenu[50] = {
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Chromium]====], [====[chromium]====]},
{[====[Firefox]====], [====[/usr/lib/firefox/firefox %u]====]},
{[====[Friends]====], [====[steam steam://open/friends]====]},
{[====[Mail Reader]====], [====[exo-open --launch MailReader %u]====]},
{[====[Pidgin Internet Messenger]====], [====[pidgin]====]},
{[====[Start Transmission Minimized]====], [====[transmission-gtk --minimized]====]},
{[====[Web Browser]====], [====[exo-open --launch WebBrowser %u]====]},
{[====[XChat IRC]====], [====[xchat]====]},
{[====[Zenmap]====], [====[zenmap %F]====]},
{[====[Zenmap (as root)]====], [====[/usr/share/zenmap/su-to-zenmap.sh %F]====]}
}
applicationsmenu[60] = {
{[====[AbiWord]====], [====[abiword]====]},
{[====[Document Viewer]====], [====[evince]====]},
{[====[LibreOffice]====], [====[libreoffice]====]},
{[====[Litecoin]====], [====[/usr/bin/litecoin-qt]====]},
{[====[New Spreadsheet]====], [====[libreoffice --calc]====]},
{[====[Print Preview]====], [====[evince-previewer]====]},
{[====[Xpdf]====], [====[xpdf %f]====]}
}
applicationsmenu[70] = {
{[====[Create Launcher on the panel]====], [====[xfce4-panel --add=launcher %u]====]},
{[====[eog]====], [====[eog %f]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[sxiv]====], [====[sxiv %F]====]},
{[====[Wine Windows Program Loader]====], [====[wine start /unix %f]====]}
}
applicationsmenu[80] = {
{[====[Bless Hex Editor]====], [====[bless %F]====]},
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt Assistant]====], [====[/usr/bin/assistant]====]},
{[====[Qt Creator]====], [====[/usr/bin/qtcreator]====]},
{[====[Qt Designer]====], [====[/usr/bin/designer]====]},
{[====[Qt Linguist]====], [====[/usr/bin/linguist]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]},
{[====[Qt4 QDbusViewer]====], [====[qdbusviewer-qt4]====]}
}
applicationsmenu[90] = {
{[====[Audacious]====], [====[audacious]====]},
{[====[Cheese]====], [====[cheese]====]},
{[====[GNOME MPlayer]====], [====[gnome-mplayer %F]====]},
{[====[guvcview]====], [====[guvcview]====]},
{[====[MPlayer Media Player]====], [====[mplayer %F]====]},
{[====[PulseAudio Volume Control]====], [====[pavucontrol]====]},
{[====[QT V4L2 test Utility]====], [====[qv4l2]====]},
{[====[Sound Recorder]====], [====[gnome-sound-recorder]====]},
{[====[Videos]====], [====[totem]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc]====]}
}
applicationsmenu[100] = {
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[Bulk Rename]====], [====[/usr/lib/Thunar/ThunarBulkRename %F]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[GParted]====], [====[/usr/sbin/gparted %f]====]},
{[====[Manage Printing]====], [====[/usr/bin/xdg-open http://localhost:631/]====]},
{[====[Open Folder with Thunar]====], [====[thunar %F]====]},
{[====[Oracle VM VirtualBox]====], [====[VirtualBox]====]},
{[====[Thunar File Manager]====], [====[thunar %F]====]},
{[====[UNetbootin]====], [====[/usr/bin/unetbootin]====]},
{[====[UXTerm]====], [====[uxterm]====]},
{[====[XTerm]====], [====[xterm]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[AMD Catalyst Control Center]====], [====[amdcccle]====]},
{[====[AMD Catalyst Control Center (Administrative)]====], [====[amdxdg-su -c amdcccle]====]},
{[====[File Manager]====], [====[thunar-settings]====]},
{[====[Multimedia Systems Selector]====], [====[gstreamer-properties]====]},
{[====[Panel]====], [====[xfce4-panel --preferences]====]},
{[====[Preferred Applications]====], [====[exo-preferred-applications]====]},
{[====[Print Settings]====], [====[system-config-printer]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]},
{[====[Removable Drives and Media]====], [====[thunar-volman-settings]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end